// components/MatchInsights.tsx
"use client";

import { usePrediction } from "@/context/PredictionContext";

export default function MatchInsights() {
  const { isLoading, result } = usePrediction();

  if (!isLoading && !result) return null;

  return (
    <section className="relative bg-[#0a1628] py-24">
      <div
        className="absolute inset-0 opacity-[0.05]"
        style={{
          backgroundImage:
            "repeating-linear-gradient(0deg, transparent, transparent 38px, white 39px), repeating-linear-gradient(90deg, transparent, transparent 38px, white 39px)",
        }}
      />

      <div className="relative mx-auto max-w-5xl px-6">
        <div className="mb-12 flex items-center gap-3">
          <span className="h-px w-6 bg-lime-400" />
          <span className="text-xs font-semibold uppercase tracking-widest text-lime-400">
            Match Insights
          </span>
        </div>

        {isLoading && <InsightsSkeleton />}

        {!isLoading && result && (
          <>
            <div className="border border-white/10 bg-white/[0.03] p-10">
              <div className="mb-6 flex items-center justify-between">
                <h3 className="text-xs font-semibold uppercase tracking-widest text-zinc-500">
                  AI Match Report
                </h3>
                <span className="text-xs font-semibold uppercase tracking-widest text-lime-400">
                  Generated by VerdictIQ AI
                </span>
              </div>

              <p className="text-lg leading-8 text-zinc-300">
                {result.team1} enters this fixture with considerably better
                recent form, winning 4 of their last 5 matches and currently
                holding a top-3 ranking. {result.team2} possesses a historically
                competitive head-to-head record but has shown inconsistency
                against top-ranked opposition in recent fixtures. Based on
                current form, ranking, and momentum, {result.winner} holds the
                statistical edge heading into this match.
              </p>

              <div className="mt-8 grid grid-cols-1 gap-4 border-t border-white/10 pt-6 sm:grid-cols-3">
                {[
                  { label: "Recent Form", value: `Favors ${result.winner}` },
                  { label: "FIFA Ranking", value: `${result.team1} #1` },
                  { label: "Head-to-Head", value: "Closely Contested" },
                ].map((item) => (
                  <div key={item.label}>
                    <p className="text-[11px] uppercase tracking-widest text-zinc-500">
                      {item.label}
                    </p>
                    <p className="mt-1 text-sm font-semibold text-white">
                      {item.value}
                    </p>
                  </div>
                ))}
              </div>
            </div>

            <div className="mt-10 border border-white/10 bg-white/[0.03] p-10">
              <h3 className="mb-8 text-xs font-semibold uppercase tracking-widest text-zinc-500">
                Team Comparison
              </h3>

              <div className="grid grid-cols-1 gap-10 md:grid-cols-2">
                <div>
                  <p className="mb-6 text-2xl font-black uppercase text-white">
                    {result.team1}
                  </p>
                  <TeamStatList
                    stats={[
                      { label: "FIFA Ranking", value: "#1" },
                      { label: "Win %", value: "78%" },
                      { label: "Goals Scored", value: "24" },
                      { label: "Goals Conceded", value: "8" },
                      { label: "Clean Sheets", value: "6" },
                      { label: "Avg. Possession", value: "58%" },
                    ]}
                  />
                </div>

                <div>
                  <p className="mb-6 text-2xl font-black uppercase text-white">
                    {result.team2}
                  </p>
                  <TeamStatList
                    stats={[
                      { label: "FIFA Ranking", value: "#3" },
                      { label: "Win %", value: "65%" },
                      { label: "Goals Scored", value: "20" },
                      { label: "Goals Conceded", value: "11" },
                      { label: "Clean Sheets", value: "4" },
                      { label: "Avg. Possession", value: "54%" },
                    ]}
                  />
                </div>
              </div>
            </div>

            <div className="mt-10 border border-white/10 bg-white/[0.03] p-10">
              <h3 className="mb-8 text-xs font-semibold uppercase tracking-widest text-zinc-500">
                Head-to-Head — Last 20 Matches
              </h3>

              <div className="grid grid-cols-3 gap-6 text-center">
                <div>
                  <p className="text-4xl font-black text-lime-400">8</p>
                  <p className="mt-2 text-xs uppercase tracking-widest text-zinc-500">
                    {result.team1} Wins
                  </p>
                </div>
                <div>
                  <p className="text-4xl font-black text-white">5</p>
                  <p className="mt-2 text-xs uppercase tracking-widest text-zinc-500">
                    Draws
                  </p>
                </div>
                <div>
                  <p className="text-4xl font-black text-white">7</p>
                  <p className="mt-2 text-xs uppercase tracking-widest text-zinc-500">
                    {result.team2} Wins
                  </p>
                </div>
              </div>

              <div className="mt-8 flex h-2 w-full overflow-hidden bg-white/10">
                <div className="h-full bg-lime-400" style={{ width: "40%" }} />
                <div className="h-full bg-zinc-600" style={{ width: "25%" }} />
                <div className="h-full bg-white/30" style={{ width: "35%" }} />
              </div>

              <div className="mt-8 grid grid-cols-2 gap-6 border-t border-white/10 pt-6 sm:grid-cols-2">
                <div>
                  <p className="text-[11px] uppercase tracking-widest text-zinc-500">
                    Goals — {result.team1}
                  </p>
                  <p className="mt-1 text-xl font-bold text-white">22</p>
                </div>
                <div>
                  <p className="text-[11px] uppercase tracking-widest text-zinc-500">
                    Goals — {result.team2}
                  </p>
                  <p className="mt-1 text-xl font-bold text-white">20</p>
                </div>
              </div>
            </div>
          </>
        )}
      </div>
    </section>
  );
}

function InsightsSkeleton() {
  return (
    <div className="space-y-10">
      {[0, 1, 2].map((i) => (
        <div
          key={i}
          className="animate-pulse border border-white/10 bg-white/[0.03] p-10"
        >
          <div className="mb-6 h-3 w-40 bg-white/10" />
          <div className="space-y-3">
            <div className="h-3 w-full bg-white/10" />
            <div className="h-3 w-5/6 bg-white/10" />
            <div className="h-3 w-2/3 bg-white/10" />
          </div>
        </div>
      ))}
    </div>
  );
}

function TeamStatList({
  stats,
}: {
  stats: { label: string; value: string }[];
}) {
  return (
    <div className="space-y-4">
      {stats.map((stat) => (
        <div
          key={stat.label}
          className="flex items-center justify-between border-b border-white/5 pb-3"
        >
          <span className="text-sm text-zinc-400">{stat.label}</span>
          <span className="text-sm font-semibold text-white">{stat.value}</span>
        </div>
      ))}
    </div>
  );
}
